version: '3'

tasks:
  zpool-create:
    cmds:
      - fallocate -l 1G vzfs.img
      - sudo zpool create -m none zedfs-pool $(pwd)/vzfs.img
    status:
      - sudo zpool status zedfs-pool
  zpool-destroy:
    cmd: sudo zpool destroy zedfs-pool

  zfs-create:
    deps:
      - zpool-create
    cmds:
      - sudo zfs create -p zedfs-pool/users
      - sudo zfs create -p -V 400M zedfs-pool/users/zedfs-user-0
      - sudo zfs create -p -V 400M zedfs-pool/users/zedfs-user-1
    status:
      - sudo zfs list zedfs-pool/users

  zfs-destroy:
    cmd: sudo zfs destroy -r zedfs-pool
  
  zfs:
    deps:
      - zpool-create
      - zfs-create

  debootstrap:
    cmd: sudo debootstrap --arch amd64 jammy ubuntu2204/ http://archive.ubuntu.com/ubuntu/
    sources:
      - test -d ubuntu2204

  systemd-nspawn-get-image:
    cmds:
      - wget -nc https://cloud-images.ubuntu.com/releases/jammy/release/ubuntu-22.04-server-cloudimg-amd64-root.tar.xz
      - machinectl import-tar --verify=no ubuntu-22.04-server-cloudimg-amd64-root.tar.xz jammy-server-cloudimg-amd64-root

  zedfs-user:
    deps:
      - zfs
      - systemd-nspawn-get-image
    cmd: >
      sudo systemd-nspawn -b --resolv-conf=replace-stub \
        --network-veth -U --settings=override \
        --bind-ro=$(pwd)/cloud-init/ds-identify.cfg:/etc/cloud/ds-identify.cfg \
        --bind-ro=$(pwd)/cloud-init/nocloud:/var/lib/cloud/seed/nocloud \
        -M jammy-server-cloudimg-amd64-root

  buildroot:
    dir: buildroot
    cmds:
      - make BR2_DEFCONFIG=../buildroot-external/configs/zedfs_defconfig O=../output BR2_EXTERNAL=../buildroot-external {{.CLI_ARGS}}
    sources:
      - buildroot-external/**/*

  buildroot-qemu:
    deps:
      - buildroot
      - zfs
    cmd: >
      sudo qemu-system-x86_64 -M microvm,x-option-roms=off,isa-serial=off,rtc=off \
        -no-acpi -enable-kvm -cpu host -nodefaults -no-user-config -nographic \
        -no-reboot -device virtio-serial-device -chardev stdio,id=virtiocon0 \
        -kernel output/images/bzImage -append "console=hvc0 root=/dev/vda rw acpi=off reboot=t panic=-1" \
        -device virtconsole,chardev=virtiocon0 \
        -netdev tap,id=tap0,script=no,downscript=no \
        -device virtio-net-device,netdev=tap0 \
        -drive id=root,file=output/images/rootfs.squashfs,format=raw,if=none \
        -device virtio-blk-device,drive=root \
        -drive id=zfs,file=/dev/zvol/zedfs-pool/users/zedfs-user-0,format=raw,if=none \
        -device virtio-blk-device,drive=zfs